package polymorphicclasses;
import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import abstractclasses.Admin;
import model.*;

public class CICSAdmin extends Admin {

    private String password; 

     public CICSAdmin() {
        super("A001", "CICS Admin", "CICS"); // default ID, name, college
        this.password = "admin123";          // default password
     }

    // Constructor 
    public CICSAdmin(String id, String name, String college) {
        super(id, name, college); // Automatically assign college as CICS
        this.password = "admin123";
  
    }

    public boolean authenticateAdmin(String id,String password) { 
        return this.getId().equals(id) && this.password.equals(password); 
    }

    // Implement the abstract method from Admin
    @Override
    public void manageSchedules() {
        System.out.println();
        System.out.println("\n\nCICS Admin " + getName() + " is managing schedules for the College of Informatics and Computing Sciences.");
    }

    // Optional: add any CICS-specific behavior
    public void generateReport() {
        System.out.println("\n\nGenerating schedule report for CICS...");
        viewSchedules(); // Reuse inherited method from Admin
    }

    //  NEW: Print ALL schedules to a .txt file
    public void printAllSchedulesToFile() {
    if (getSchedules().isEmpty()) {
        System.out.println("No schedules available to print.");
        return;
    }

    String fileName = "CICS_Admin_" + getName().replaceAll(" ", "_") + "_All_Schedules.txt";

    try (FileWriter writer = new FileWriter(fileName)) {
        writer.write("=== Schedule Report for " + getCollege() + " ===\n");
        writer.write("Generated by Admin: " + getName() + " (" + getId() + ")\n\n");

        for (Schedule s : getSchedules()) {
            // Format time properly
            String formattedStart = s.getTime().getStart().format(DateTimeFormatter.ofPattern("h:mm a"));
            String formattedEnd = s.getTime().getEnd().format(DateTimeFormatter.ofPattern("h:mm a"));

            writer.write("Schedule ID: " + s.getSchedID() + "\n");
            writer.write("Program: " + s.getProgram().getProgramName() + "\n");
            writer.write("Section: " + s.getSection() + "\n");
            writer.write("Professor: " + s.getProfessor().getName() + "\n");
            writer.write("Day: " + s.getDay() + "\n");
            writer.write("Time: " + formattedStart + " - " + formattedEnd + "\n");
            writer.write("Room: " + s.getRoom().getRoomName() + " (Cap: " + s.getRoom().getCapacity() + ")\n");
            writer.write("------------------------------------------\n");
        }

        writer.write("\nTotal Schedules: " + getSchedules().size() + "\n");
        writer.write("Report Generated Successfully.\n");

        System.out.println("All schedules saved to: " + fileName);

    } catch (IOException e) {
        System.out.println("Error while writing to file: " + e.getMessage());
    }
}


    @Override
    public void roleDescription() {
        System.out.println(getName() + " is an admin responsible for managing schedules in " + getCollege() + ".");
    }

    public ArrayList<Schedule> getAllSchedules() {
    return schedules;
    }

    // put inside CICSAdmin class
public Schedule findScheduleById(String id) {
    if (id == null) return null;
    for (Schedule s : getSchedules()) { // getSchedules() is inherited from Admin
        if (s.getSchedID().equalsIgnoreCase(id.trim())) {
            return s;
        }
    }
    return null;
}






}
